// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddUser(arg1, arg2) {
  return window['go']['main']['App']['AddUser'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsSetupComplete() {
  return window['go']['main']['App']['IsSetupComplete']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function SetupRoot(arg1, arg2) {
  return window['go']['main']['App']['SetupRoot'](arg1, arg2);
}
