// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddUser(arg1:string,arg2:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function IsSetupComplete():Promise<boolean>;

export function Login(arg1:string,arg2:string):Promise<boolean>;

export function SetupRoot(arg1:string,arg2:string):Promise<void>;
